//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PickleStudio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PickleStudio.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string EditCopyText {
            get {
                return ResourceManager.GetString("EditCopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string EditCopyToolTipText {
            get {
                return ResourceManager.GetString("EditCopyToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string EditCutText {
            get {
                return ResourceManager.GetString("EditCutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string EditCutToolTipText {
            get {
                return ResourceManager.GetString("EditCutToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Line Numbers.
        /// </summary>
        public static string EditorDisplayLineNumbersText {
            get {
                return ResourceManager.GetString("EditorDisplayLineNumbersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle display of line numbers.
        /// </summary>
        public static string EditorDisplayLineNumbersToolTipText {
            get {
                return ResourceManager.GetString("EditorDisplayLineNumbersToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Symbols.
        /// </summary>
        public static string EditorDisplaySymbolsText {
            get {
                return ResourceManager.GetString("EditorDisplaySymbolsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle display of non-character symbols.
        /// </summary>
        public static string EditorDisplaySymbolsToolTipText {
            get {
                return ResourceManager.GetString("EditorDisplaySymbolsToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Wrap.
        /// </summary>
        public static string EditorWordWrapText {
            get {
                return ResourceManager.GetString("EditorWordWrapText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle word wrap.
        /// </summary>
        public static string EditorWordWrapToolTipText {
            get {
                return ResourceManager.GetString("EditorWordWrapToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string EditPasteText {
            get {
                return ResourceManager.GetString("EditPasteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string EditPasteToolTipText {
            get {
                return ResourceManager.GetString("EditPasteToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string EditRedoText {
            get {
                return ResourceManager.GetString("EditRedoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string EditRedoToolTipText {
            get {
                return ResourceManager.GetString("EditRedoToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string EditUndoText {
            get {
                return ResourceManager.GetString("EditUndoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string EditUndoToolTipText {
            get {
                return ResourceManager.GetString("EditUndoToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string FileCloseText {
            get {
                return ResourceManager.GetString("FileCloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close current project or feature.
        /// </summary>
        public static string FileCloseToolTipText {
            get {
                return ResourceManager.GetString("FileCloseToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Files (.csproj, .feature)|*.csproj;*.feature.
        /// </summary>
        public static string FileOpenFilter {
            get {
                return ResourceManager.GetString("FileOpenFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string FileOpenText {
            get {
                return ResourceManager.GetString("FileOpenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project or feature file.
        /// </summary>
        public static string FileOpenToolTipText {
            get {
                return ResourceManager.GetString("FileOpenToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        public static string FileSaveAllText {
            get {
                return ResourceManager.GetString("FileSaveAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all files.
        /// </summary>
        public static string FileSaveAllToolTipText {
            get {
                return ResourceManager.GetString("FileSaveAllToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string FileSaveText {
            get {
                return ResourceManager.GetString("FileSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current file.
        /// </summary>
        public static string FileSaveToolTipText {
            get {
                return ResourceManager.GetString("FileSaveToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application makes use of the following third party components:.
        /// </summary>
        public static string HelpAboutDialogText {
            get {
                return ResourceManager.GetString("HelpAboutDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string HelpAboutText {
            get {
                return ResourceManager.GetString("HelpAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string HelpAboutToolTipText {
            get {
                return ResourceManager.GetString("HelpAboutToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Project.
        /// </summary>
        public static string NoProjectName {
            get {
                return ResourceManager.GetString("NoProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Settings.
        /// </summary>
        public static string SettingsLoadText {
            get {
                return ResourceManager.GetString("SettingsLoadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load settings.
        /// </summary>
        public static string SettingsLoadToolTipText {
            get {
                return ResourceManager.GetString("SettingsLoadToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        public static string SettingsSaveText {
            get {
                return ResourceManager.GetString("SettingsSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        public static string SettingsSaveToolTipText {
            get {
                return ResourceManager.GetString("SettingsSaveToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string TestRunText {
            get {
                return ResourceManager.GetString("TestRunText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run tests.
        /// </summary>
        public static string TestRunToolTipText {
            get {
                return ResourceManager.GetString("TestRunToolTipText", resourceCulture);
            }
        }
    }
}
